version: '3'
services:
  db:
    image: postgres:16
    container_name: tasks_db
    environment:
      POSTGRES_USER: jadith
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  db_data:


